controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - link0_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
      - link5_link6_joint
  - name: gripper_controller
    joints:
      - link6_link7_joint
