controller_list:
  - name: fake_manipulator_controller
    joints:
      - link0_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
      - link5_link6_joint
  - name: fake_gripper_controller
    joints:
      - link6_link7_joint